### PR TITLE
(Resolves #17) basic styling

### LINKED ISSUE #17: Add basic styling
Implement basic styling for questions list + question answer view (we can split this into two tickets).
We can use Bootstrap for this, or something more fancy/lighter - it's up to the devs.

### PR DESCRIPTION
**Pull request by stanislawK**
Resolves #17

### CODE REVIEW

**Review by maciejsobolewski — CHANGES_REQUESTED** [review]
Wow, so much better.
One detail though:
Screenshot_2022-08-05_14-03-27
Some padding under the question content would be nice + each answer in the newline.

**Comment by stanislawK** [comment]
> 

Hopefully now it looks better. I've added also styling for stats component, and some color touches which might look familiar.

**Review by maciejsobolewski — CHANGES_REQUESTED** [review]
Looks a lot better.
But why include all these css and svgs? Shouldn't it be installed as a package?

**Comment by stanislawK** [comment]
>
PyPi packages which I found are outdated by 7-8 years now, and I did not wanted to use cdns.

**Comment by maciejsobolewski** [comment]
> > 
> 
> PyPi packages which I found are outdated by 7-8 years now, and I did not wanted to use cdns.

Still, adding these files to the repo is a bad practice.
Can't we use npm package for that?

**Comment by stanislawK** [comment]
> Can't we use npm package for that?

Most of that files are icon-related and not included in node package https://zurb.com/playground/foundation-icon-fonts-3
Since currently we are using only one icon, I can try to remove most of them, and logic around them inside files.

**Review by maciejsobolewski — APPROVED** [review]

**Pull request merged**
